global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'rankmybrand-crawler'

scrape_configs:
  - job_name: 'web-crawler'
    static_configs:
      - targets: ['web-crawler:9091']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

rule_files:
  - 'alerts.yml'
